import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import { CampusProvider } from "@/contexts/campus-context";
import { AuthProvider } from "@/contexts/auth-context";
import { ThemeProvider } from "@/contexts/theme-context";
import { NotificationProvider } from "@/contexts/notification-context";
import { QueryProvider } from "@/providers/query-provider";
import { ToastContainer } from "react-toastify";
import { NotificationToast } from "@/components/ui/notification-toast";
import { Toaster } from "@/components/ui/toaster";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-r from-blue-950 via-blue-900 via-30% via-purple-600 via-45% via-blue-900 via-60% to-indigo-950 animated-gradient`}
      >
        <QueryProvider>
          <AuthProvider>
            <ThemeProvider>
              <NotificationProvider>
                <CampusProvider>
                  {children}
                  <NotificationToast />
                  <Toaster />
                </CampusProvider>
              </NotificationProvider>
              <ToastContainer
                position="top-right"
                autoClose={3000}
                hideProgressBar={false}
                newestOnTop
                closeOnClick
                rtl={false}
                pauseOnFocusLoss
                draggable
                pauseOnHover
                theme="colored"
              />
            </ThemeProvider>
          </AuthProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
